### ISSUE TITLE
Each topic should have a schema

### ISSUE THREAD

**Issue by nicoonoclaste** [realraum/door_and_sensors#3]
Each MQTT channel (that uses JSON) should have its message format described as a [JSON Schema](http://json-schema.org/) (possibly in YAML, because JSON is a pain to write  :P) and the MQTT brocker should log non-conforming messages.

**Comment by btittelbach** [comment]
good idea.. please feel free to edit
https://realraum.at/wiki/doku.php?id=roomauto:mqtt_topics#nd_level_topics_and_payload_types
accordingly

**Comment by nicoonoclaste** [comment]
@btittelbach If that's alright with you, I would rather autogenerate descriptions out of the manifest, rather than having manifests in the wiki: it keeps up honest and the doc up-to-date.

**Comment by btittelbach** [comment]
sounds good.

Most up-to-date specification of JSON Messages are currently these two files:
https://github.com/realraum/door_and_sensors/blob/master/r3events/basicevents.go
https://github.com/realraum/door_and_sensors/blob/master/r3events/basicevents.go

would be nice to have a json schema made from those.
We could update ugly https://github.com/realraum/door_and_sensors/blob/master/r3events/marshal_events.go to use https://github.com/xeipuuv/gojsonschema and use the schemas directly.
Thus store the definition in only one place.

btw: look at http://jsonschema.net/index.html , might make the work easier.

**Comment by nicoonoclaste** [comment]
Looks like only loading/validation is implemented in [gojsonschema](https://github.com/xeipuuv/gojsonschema)
