### ISSUE TITLE
Closing door does not switch off Lights

### ISSUE THREAD

**Issue by gebi** [realraum/door_and_sensors#4]
Hi,

happened on 17.3.

Just general bug or message gone missing through mqtt?

**Comment by btittelbach** [comment]
grml.. and I just debugged a similar problem for 2 hours yesterday, fixed two daemons as a result and everything worked fine afterwards. (see https://github.com/realraum/deckenlichtschalter/commit/8ecdcf779019723e91e022911689bd166583d87b and https://github.com/realraum/door_and_sensors/commit/5e5f09d3579ca9c618184d001c8c902b2243bc0a)

I seems that dostuff_switch_lights.py can still get stuck forever somewhere,
though I haven't figure out the conditions yet. It was supposed to be a script so simple it replaces any other configuration file... and yet.. python sucks.
Take a look?

https://github.com/realraum/door_and_sensors/blob/master/scripts/dostuff_switch_lights.py

**Comment by btittelbach** [comment]
such a stupid typo.... hopefully fixed with https://github.com/realraum/deckenlichtschalter/commit/b07ddb835f21ebf29b98d285f1b88a15a1b50fb2
