### ISSUE TITLE
overtemp has no description in the wiki

### ISSUE THREAD

**Issue by PeterTheOne** [realraum/door_and_sensors#5]
`realraum/olgafreezer/overtemp` has no description in the wiki. Also what should one do when it happens.

**Comment by btittelbach** [comment]
I added the verbal description.
The message format however was already described here: https://realraum.at/wiki/doku.php?id=roomauto:mqtt_topics and already included all this information except telling you what to do. That's probably something that varies from individual sensor to sensor and so I think either a human or a spearate expert system like script ;-> should decide on what to do with this information.

**Comment by btittelbach** [comment]
actually the information was already in the wiki, just not visible due to a missing tablerow termination character

**Comment by PeterTheOne** [comment]
Thanks!

> a human or a spearate expert system like script ;-> should decide on what to do with this information.

Maybe two sentences and a picture of the olgafreezer in the wiki would make due. :)
